name: learn-github-actions
on:
  push:
    branches:
      - main
      - develop

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v

  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      # - run: bats -v
      - run: npm i simple-npm-package
      - run: ls -l
